### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by teovoinea** [snipsco/tract#128]
I noticed in the CI scripts, windows builds aren't tested.

Are there any plans to support windows in the future?

**Comment by kali** [comment]
Hi, thanks for your interest!

Windows support is a very low priority issue for both snips and myself. We don't know if tract works under windows (it may work out of the box, honestly), and as you noticed we don't have any CI coverage for windows.

That said, I'll gladly help you to get tract to work on windows if it does not. I would also be very happy to merge a PR with a very basic windows CI. Feel free to give it a shot if you want :)

**Comment by kali** [comment]
FYI #160
