### ISSUE TITLE
`model.into_optimized()` consumes too much RAM - crashes

### ISSUE THREAD

**Issue by psiphi75** [snipsco/tract#145]
When I call `model.into_optimized()` the RAM consumption of the process grows very quickly to run out of all available RAM. The OS (Linux in this case) kills the process after a while. The 800 kB model below consumed at least 12 GB of RAM before the process was killed.

Below is the code I use (compiled using `--release`):

```Rust
fn main() -> TractResult<()> {
  let path = Path::new("GRU128KeywordSpotter-v2-10epochs.onnx");
  let mut model = tract_onnx::onnx().model_for_path(path)?;
  model.set_input_fact(0, TensorFact::dt_shape(f32::datum_type(), tvec!(1, 1, 80)))?;

  let model = model.into_optimized()?;  // This never completes

  let plan = SimplePlan::new(&model)?;

}
```

The sample ONNX file can be found here: https://psiphi75.github.io/workingfiles/GRU128KeywordSpotter-v2-10epochs.onnx

**Comment by kali** [comment]
Thanks, I'll have a look soon.

**Comment by kali** [comment]
@psiphi75 hey, just a quick work to say I have not forget about this issue :) I'm trying to close a huge refactoring of some internals of tract that is keeping me very busy and so I'm trying not to disperse my attention too much. But I'll come back to this soon.

**Comment by kali** [comment]
Hey, finally had a look at your model ! I tested against the current master (6ea629d8c) and I count not observe what you describe. That said, the model does not run as is. The gather model has a negative argument and the code does not deal with that correctly. I will fix this soon (over the weekend hopefully).

Would you allow me to add this model to my collection of models to test during CI ? GRU coverage is very weak as of today... It would imply that I upload it to a publicly available bucket, with the url in the repo. Tell me what you think :)

**Comment by psiphi75** [comment]
That’s great, thanks.  Yes, you are free to use the model as you wish, thank you for asking.

**Comment by kali** [comment]
d71a06a0 fixed the Gather issue. I was able to load and bench the network.

**Comment by psiphi75** [comment]
Thanks.  I finally got to test it out using the latest master branch and it works!
