### ISSUE TITLE
"cargo update" brings in a protobuf version (2.9.0) that doesn't compile.

### ISSUE THREAD

**Issue by hrydgard** [snipsco/tract#173]
Try to just run cargo update in the root directory, then cargo build.

Some cargo.toml dependency needs to be tightened down, or things need to be fixed to work with the new version of protobuf.

I first thought the culprit was harness/onnx-test-suite/debug-utils/Cargo.toml where it's set to "*", but no dice changing that.

**Comment by kali** [comment]
yeah, i'm on it:)

**Comment by kali** [comment]
The CI broke last night, actually, so I was aware. Thanks for the heads-up.

**Comment by hrydgard** [comment]
Cool, haven't watched your CI :) 

Seems that rust-protobuf accidentally pushed a busted version:
https://github.com/stepancheg/rust-protobuf/commit/721e3ffa38a7ffac16ae9be92953a25124d7b9d5

**Comment by hrydgard** [comment]
Might want to consider checking in Cargo.lock by the way. The diffs aren't the prettiest, but it firmly blocks this sort of third-party breakage.

**Comment by kali** [comment]
It's a bit more subtle, I actually commit the protobuf generated files. I did that a long time ago when the protobuf generator required a working protoc on the platform, and that was raising all kind of issues on build/CI machines. And right now we have a 2.18 (or lower, haven't checked) generated files that are incompatible with the new 2.19 generator... So if you're using the "correctly", the version is not a bust.

Now that we have a more build.rs self-contained generated, I will maybe move back the generation in build.rs. I plan to try that this afternoon.

As for commiting Cargo.lock, it may help for the command line too, but it is ignore for libraries, so it's only a partial fix.

**Comment by hrydgard** [comment]
In that case though I should be able to get back to a locally working state by modifying your protobuf = dependencies to an older version. 

But I only find 
```
harness/onnx-test-suite/Cargo.toml:protobuf = "2.4.2"
harness/onnx-test-suite/debug-utils/Cargo.toml:protobuf = "*"
onnx/Cargo.toml:protobuf = "2.0"
tensorflow/Cargo.toml:protobuf = "2.0"
```
None of them are set to just 2, which would result in the automatic upgrade from 2.18 to 2.19 you are describing. Or do you mean 2.0.18 and 2.0.19 ?  I tried forcing them to 2.0.18 which didn't work.

**Comment by kali** [comment]
Ho, sorry, did not realise you were actually stuck. I have pushed a "bump" branch here with a temporary fix (re-generating the files by hand). https://github.com/snipsco/tract/pull/175

It should unstuck you, while I'm doing the right thing, and getting those generated files out of git.

I think you may have been able to workaround by doing some targetted cargo updates (`cargo update -p protobuf --precise 2.0.18` or something like that to revert the version bump, but now I guess you'd better try the `bump` branch.

**Comment by hrydgard** [comment]
Cool, thanks! Bump branch seems fine.

**Comment by kali** [comment]
0.5.3 should fix it ! Thanks for your patience :)

**Comment by kali** [comment]
except... now that new version of protobuf has been yanked.

Will fix and release again

**Comment by kali** [comment]
So, 0.5.4 should do the trick... wow, what a week.

**Comment by hrydgard** [comment]
Great! And the week has only just started :)

**Comment by kali** [comment]
Hey @hrydgard, are we ok to close this one ?

**Comment by hrydgard** [comment]
Yeah, sorry, it's all good now.
