### ISSUE TITLE
Could not resolve inputs at top-level

### ISSUE THREAD

**Issue by flipflopx** [snipsco/tract#177]
When I try loading a model with `tract_onnx::onnx().model_for_read()` I get this error message: `Could not resolve inputs at top-level: [""]`

Any idea why this happens?

**Comment by kali** [comment]
Hi, thanks for your interest in tract !

This error used to happen with models making use of optional inputs, but I thought it was behind us. Are you using a recent version of tract ?

Would it be possible to share the model with me so I can investigate ?

**Comment by kali** [comment]
Hey @flipflopx , is there anything I can do to help, or should we close this ticket ?

**Comment by kali** [comment]
All right, closing now. Feel free to open up again if you get more information to feed me.
