### ISSUE TITLE
Missing node type: AddV2

### ISSUE THREAD

**Issue by hrydgard** [snipsco/tract#180]
Tensorflow 2 has started outputting a new kind of Add node, AddV2, here and there, which seems to be the same. It's not yet supported by Tract. It might be possible to, as a first step, simply accept AddV2 as an alternate name for Add but otherwise treat it the same, but I'm not 100% sure about this.

**Comment by kali** [comment]
I agree it does look the same. If you want to try it on your side and check you get the expected result, it's as simple as registering the operator in `tensorflow/src/ops/math.rs`. It would be nice if you can confirm it does what you expect before I add it as I don't have much to check it. You'll also notice that there is already a BiasAdd that is the same as Add...

Waiting for the PR :)

**Comment by hrydgard** [comment]
PR is there, and it works fine :)
