### ISSUE TITLE
armv7 has TEXTREL

### ISSUE THREAD

**Issue by pruthvikar** [snipsco/tract#211]
Building the library for armv7 creates a library with TEXTRELs.

TEXTRELs are [not compatible with Android API Level 23 and above](https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#text-relocations-enforced-for-api-level-23
).

When built for `armv7-linux-androideabi`

> `AR=arm-linux-androideabi-ar CC=armv7a-linux-androideabi29-clang cargo build --target armv7-linux-androideabi
> `

`scanelf` then gives

> ```
> scanelf -qT target/armv7-linux-androideabi/release/libandroid.so
>   libandroid.so: (memory/data?) [0x57E9F8] in (optimized out: previous $d.1) [0x57E9C0]
>   libandroid.so: (memory/data?) [0x57EC70] in (optimized out: previous $d.1) [0x57EC3C]
>   target/armv7-linux-androideabi/release/libandroid.so
> ```

**Comment by kali** [comment]
Hey @pruthvikar, thanks for your interest and the report !

I think I've find what was wrong, even if I'm not 100% sure why the `ldr` pseudo statement was not working as it was generating a PC-relative address.

Would you please be able to check that the PR fixes the issue completely ?

**Comment by pruthvikar** [comment]
Just checked and the TEXTREL's have gone.

Thanks!

**Comment by kali** [comment]
Great, release 0.5.8 has these fixes.
