### ISSUE TITLE
Optimization fails due to Rank mismatch, InferenceModel works

### ISSUE THREAD

**Issue by tgolsson** [snipsco/tract#232]
Hi!

After updating some of our ONNX generators, we're seeing failures during the optimization step for tract. The error we get is as follows:

```
Failed analyse for node #23 "Min__6" MinNary
Infering facts: "Applying rule inputs[0].rank == inputs[1].rank: Impossible to unify 2 with 0."
```

This is based on tensorflow code that looks like this:

```python
x = tf.clip_by_value(x, MIN, MAX)
```

Where result is a `[BATCH, x]` tensor, and both `MIN` and `MAX` are constant scalars `[-20, 2]`. The file renders fine with Netron, and as noted works without optimizations, so I'm guessing this is simply an unhandled case somewhere for the scalar min case during optimizations? I'm unfortunately unable to find out where this should be handled, but if you can point me in the right direction I can take a stab at fixing it in a PR.

**Comment by kali** [comment]
Hey ! Thanks for the report.

I would be curious to see how this is translated in onxx form. Maybe you could run tract CLI with something like that to help find out.

```
tract model.onnx --pass load dump
```

I assume it translated to a n-ary min then a n-ary max. And the n-ary broadcasting in its current form looks broken. If you're curious the code is in core/src/ops/binary.rs, but I'm doing a big refactor so it may not be the best time for you to dive in this code. If you could check and show me the relevant part of the dump, I can probably produce a fix today, though.

**Comment by kali** [comment]
Also, if you control the Onnx generators code, a workaound may be to translate to the Onnx Clip operator which should not exhibit the problem.

**Comment by tgolsson** [comment]
Thanks for the response @kali! Below is the relevant section from the dump. We unfortunately do not control the generator, but it is indeed odd that it does not use an onnx clip operator - but it might something that is decomposed already on the Tensorflow side.

```
┝┷ 20 AddInference StatefulPartitionedCall/.../BiasAdd
││   * input fact  #0: 19/0> ..x?
││     input fact  #1: 5/0> 84xF32 /*snip */
││   * output fact #0: ..x? >23/0 
│┝┷ 23 MinNary Min__6
││   * input fact  #0: 20/0> ..x?
││     input fact  #1: 11/0> F32 2
││   * output fact #0: ..x? >24/0 
│┝┷ 24 MaxNary Max__9
││   * input fact  #0: 23/0> ..x?
││     input fact  #1: 10/0> F32 -20
││   * output fact #0: ..x? >25/0 
│┝ 25 Exp StatefulPartitionedCall/.../Exp
││   * input fact  #0: 24/0> ..x?
││   * output fact #0: ..x? >26/0 
```

**Comment by kali** [comment]
Thanks ! This is what I thought. I'll try to address this today.

**Comment by tgolsson** [comment]
@kali Let me know if you want me to test anything.

**Comment by kali** [comment]
Hey @tgolsson, i was not able to device a unit test reproducing your issue... Could you give a shot to #234 ?

**Comment by tgolsson** [comment]
@kali Testing right now. I'll check both optimized and normalized, do you want me to test any other cases?

**Comment by kali** [comment]
Nope, it should be enough if all is working.

**Comment by tgolsson** [comment]
@kali My benchmarks pass with the change, on all three levels of optimization.

**Comment by kali** [comment]
Well, the change is tiny enough and just feels right. I'm cutting a 0.5.11 right now.

**Comment by kali** [comment]
@tgolsson ok to close ?

**Comment by tgolsson** [comment]
I've not had time to deploy it in production unfortunately, but it seemed to work well enough on my machine. I'll close this for now. Thanks for the fix!
