### ISSUE TITLE
Build failing for stable-x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by joverwey** [snipsco/tract#320]
On Windows, the only way to use the debugger in CLion is to use the GNU toolchain.
Unfortunately tract does not compile using this. I get the following error:   

```
Compiling tract-linalg v0.9.2
error: failed to run custom build command for `tract-linalg v0.9.2`

Caused by:
  process didn't exit successfully: `D:\temp\hello_onnx\target\debug\build\tract-linalg-3c598281dbd21f17\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Could not find lib.exe', C:\Users\johan\.cargo\registry\src\github.com-1ecc6299db9ec823\tract-linalg-0.9.2\build.rs:16:17
```

To reproduce:

```
rustup default stable-x86_64-pc-windows-gnu
cargo build
```

**Comment by kali** [comment]
Right. linalg `build.rs` only checks for windows, and then assumes msvc toolchain.

I am no windows expert, but I can have a look. I just have the msvc toolchain installed... What would be the "regular" way to get a GNU toolchain on windows these day ? cygwin ? chocolatey ?

**Comment by joverwey** [comment]
> Right. linalg `build.rs` only checks for windows, and then assumes msvc toolchain.
> 
> I am no windows expert, but I can have a look. I just have the msvc toolchain installed... What would be the "regular" way to get a GNU toolchain on windows these day ? cygwin ? chocolatey ?

I use [MSys2](https://www.msys2.org/).

Thanks!

**Comment by kali** [comment]
Hey, would you care to try #321 ?
