### ISSUE TITLE
List of ONNX suppoted ops

### ISSUE THREAD

**Issue by WilliamTambellini** [snipsco/tract#74]
Just a page/.md with the list of supported ONNX ops.
Also unclear from the main .md page which version of onnx/opset does tract support.
Tks.

**Comment by aldanor** [comment]
Just a thought, could check in a shell script that auto-refreshes this as well (provided that the ops that are supported are supported in full).

**Comment by kali** [comment]
@WilliamTambellini As of today, the strategy for ONNX support has been to implement as many test cases as possible. I have not worked specifically to choose and target an opset version yet.

The list of passing backend checks are in the text files in https://github.com/snipsco/tract/tree/master/onnx/tests , and they are run by the continuous integration.

While the plan is to get at 100% there, this strategy means that anything not tested may not be implemented (and the spec is actually wider than the tests in many locations).

That said, we could at least generate a list of known operators, maybe with associated passing tests for the ones in nodes. I will try to make that happen in the command line, so at least it should be easy to update a list.

As of today, there is no real test coverage for non-f32 types, but many operators will work with f64 or integers when it makes sense (f16 is a bit more tricky). Recurring ops are not supported (I have a bit of LSTM in a branch, but the test coverage is very poor, so I have decided against merging it), and control flow are not covered either.

**Comment by WilliamTambellini** [comment]
ok tks
